# Generated by Django 4.0.4 on 2022-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='patient',
            field=models.ManyToManyField(to='mysite.patient'),
        ),
        migrations.AddField(
            model_name='treatdoctor',
            name='patient',
            field=models.ManyToManyField(to='mysite.patient'),
        ),
    ]
