# Generated by Django 4.0.4 on 2022-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_hospital_type_of_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type_of_hospital',
            field=models.CharField(choices=[('Государственная', 'Государственная'), ('Частная', 'Частная')], max_length=255),
        ),
        migrations.AlterField(
            model_name='treatdoctor',
            name='patient',
            field=models.ManyToManyField(related_name='patient', to='mysite.patient'),
        ),
    ]
