# Generated by Django 4.0.4 on 2022-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_hospital_type_of_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatdoctor',
            name='patient',
            field=models.ManyToManyField(to='mysite.patient'),
        ),
    ]
