# Generated by Django 4.0.4 on 2022-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_treatdoctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatdoctor',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='nurse',
            field=models.ManyToManyField(to='mysite.nurse'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treat_doctor',
            field=models.ManyToManyField(to='mysite.treatdoctor'),
        ),
    ]
