# Generated by Django 4.0.4 on 2022-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_patient_nurse_remove_patient_treat_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatdoctor',
            name='patient',
            field=models.ManyToManyField(related_name='patients', to='mysite.patient'),
        ),
    ]
