# Generated by Django 4.0.4 on 2022-05-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_treatdoctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatdoctor',
            name='patient',
        ),
        migrations.AddField(
            model_name='treatdoctor',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.patient'),
            preserve_default=False,
        ),
    ]
