# Generated by Django 4.0.4 on 2022-05-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
